version: '3'
services:
  model:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      # assume you have installed pulled model locally already
      - /Users/binchen/.ollama/:/root/.ollama
    tty: true
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 7654:7654
    environment:
      # when model running in local host
      # - MODEL_URL=http://host.docker.internal:11434
      - MODEL_URL=http://model:11434
    depends_on:
      - model
